apiVersion: v1
kind: Service
metadata:
  name: order-ms-service
spec:
  selector:
    app: order-ms # <-- Empareja con el label del Deployment
  type: ClusterIP # <-- Solo accesible internamente
  ports:
    - protocol: TCP
      port: 80 # Puerto del Service
      targetPort: 8082 # Puerto del contenedor